site_name: MicroRaft
site_description: 'MicroRaft: Java implementation of the Raft consensus algorithm'
site_url: https://microraft.io
site_author: 'Ensar Basri Kahveci'
copyright: 'MicroRaft, 2020. Open-sourced by <a href="https://twitter.com/metanet" target="_blank">Ensar Basri Kahveci</a>'
docs_dir: src
use_directory_urls: true
theme: bootstrap4
google_analytics: ['UA-485423-8', 'MicroRaft']

plugins:
  - search

markdown_extensions:
  - attr_list
  - fenced_code

nav:
  - 'User Guide':
      - Setup: 'user-guide/setup.md'
      - APIs and Main Abstractions: 'user-guide/apis-and-main-abstractions.md'
      - Configuration: 'user-guide/configuration.md'
      - 'Tutorial: Building an Atomic Register': 'user-guide/tutorial-building-an-atomic-register.md'
      - Resiliency and Fault Tolerance: 'user-guide/resiliency-and-fault-tolerance.md'
      - Monitoring: 'user-guide/monitoring.md'
      - Release Notes: 'user-guide/release-notes.md'
      - Roadmap: 'user-guide/roadmap.md'
  - 'Deep Dive':
      - Architecture: 'documentation/architecture.md'
      - Leader Election: 'documentation/leader-election.md'
      - Log Replication: 'documentation/log-replication.md'
      - Snapshotting: 'documentation/snapshotting.md'
      - Persistence: 'documentation/persistence.md'
  - 'Javadoc':
      - '1.0': 'javadoc/1.0/index.html'
  - Github: 'https://github.com/MicroRaft/MicroRaft'
  - Slack: 'https://join.slack.com/t/microraft/shared_invite/zt-dc6utpfk-84P0VbK7EcrD3lIme2IaaQ'
  - '@MicroRaft': 'https://twitter.com/MicroRaft'
