site_name: MicroRaft
site_description: 'MicroRaft: Java implementation of the Raft consensus algorithm'
site_url: https://microraft.io
site_author: 'Ensar Basri Kahveci'
copyright: 'MicroRaft, 2020. Ensar Basri Kahveci'
docs_dir: src
use_directory_urls: true
theme: bootstrap4
google_analytics: ['UA-485423-8', 'MicroRaft']

plugins:
  - search

markdown_extensions:
  - attr_list
  - fenced_code

nav:
  - 'User Guide':
      - Getting Started: 'user-guide/getting-started.md'
      - Main Abstractions: 'user-guide/main-abstractions.md'
      - Configuration: 'user-guide/configuration.md'
      - How to Use MicroRaft: 'user-guide/how-to-use-microraft.md'
      - Fault Tolerance: 'user-guide/fault-tolerance.md'
      - Release Notes: 'user-guide/release-notes.md'
  - 'Documentation':
      - Architecture: 'documentation/architecture.md'
      - Leader Election: 'documentation/leader-election.md'
      - Log Replication: 'documentation/log-replication.md'
      - Snapshotting: 'documentation/snapshotting.md'
      - Persistence: 'documentation/persistence.md'
      - Roadmap: 'documentation/roadmap.md'
  - 'Javadoc':
      - '1.0': 'javadoc/1.0/index.html'
  - Github: 'https://github.com/metanet/microraft'
  - Slack: 'https://join.slack.com/t/microraft/shared_invite/zt-dc6utpfk-84P0VbK7EcrD3lIme2IaaQ'
