site_name: MicroRaft
use_directory_urls: true

theme: bootstrap4

plugins:
  - search

markdown_extensions:
  - attr_list
  - fenced_code

nav:
  #  - Home: 'index.md'
  - 'User Guide':
      - Getting Started: 'user-guide/getting-started.md'
      - Main Abstractions: 'user-guide/main-abstractions.md'
      - Configuration: 'user-guide/configuration.md'
      - How to Use MicroRaft: 'user-guide/how-to-use-microraft.md'
      - Fault Tolerance: 'user-guide/fault-tolerance.md'
  - 'Internals':
      - Threading and Execution Model: 'internals/threading-and-execution-model.md'
      - Leader Election: 'internals/leader-election.md'
      - Log Replication: 'internals/log-replication.md'
      - Snapshotting: 'internals/snapshotting.md'
      - Persistence: 'internals/persistence.md'
  - 'Release Notes':
      - 1.0: 'release-notes/1-0.md'

